// Mocks generated by Mockito 5.4.4 from annotations
// in git_users_app/test/layers/domain/usecase/history_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:math' as _i4;

import 'package:git_users_app/layers/data/datasources/history_datasource.dart'
    as _i3;
import 'package:git_users_app/layers/domain/models/dtos/history_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIterator_0<E> extends _i1.SmartFake implements Iterator<E> {
  _FakeIterator_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHistoryDto_1 extends _i1.SmartFake implements _i2.HistoryDto {
  _FakeHistoryDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HistoryDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryDatasource extends _i1.Mock implements _i3.HistoryDatasource {
  MockHistoryDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.HistoryDto> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: <_i2.HistoryDto>[],
      ) as List<_i2.HistoryDto>);

  @override
  void add(_i2.HistoryDto? historyDto) => super.noSuchMethod(
        Invocation.method(
          #add,
          [historyDto],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [List].
///
/// See the documentation for Mockito's code generation for more information.
class MockList extends _i1.Mock implements List<_i2.HistoryDto> {
  MockList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set first(_i2.HistoryDto? value) => super.noSuchMethod(
        Invocation.setter(
          #first,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set last(_i2.HistoryDto? value) => super.noSuchMethod(
        Invocation.setter(
          #last,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
      ) as int);

  @override
  set length(int? newLength) => super.noSuchMethod(
        Invocation.setter(
          #length,
          newLength,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Iterable<_i2.HistoryDto> get reversed => (super.noSuchMethod(
        Invocation.getter(#reversed),
        returnValue: <_i2.HistoryDto>[],
      ) as Iterable<_i2.HistoryDto>);

  @override
  Iterator<_i2.HistoryDto> get iterator => (super.noSuchMethod(
        Invocation.getter(#iterator),
        returnValue: _FakeIterator_0<_i2.HistoryDto>(
          this,
          Invocation.getter(#iterator),
        ),
      ) as Iterator<_i2.HistoryDto>);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
      ) as bool);

  @override
  _i2.HistoryDto get first => (super.noSuchMethod(
        Invocation.getter(#first),
        returnValue: _FakeHistoryDto_1(
          this,
          Invocation.getter(#first),
        ),
      ) as _i2.HistoryDto);

  @override
  _i2.HistoryDto get last => (super.noSuchMethod(
        Invocation.getter(#last),
        returnValue: _FakeHistoryDto_1(
          this,
          Invocation.getter(#last),
        ),
      ) as _i2.HistoryDto);

  @override
  _i2.HistoryDto get single => (super.noSuchMethod(
        Invocation.getter(#single),
        returnValue: _FakeHistoryDto_1(
          this,
          Invocation.getter(#single),
        ),
      ) as _i2.HistoryDto);

  @override
  List<R> cast<R>() => (super.noSuchMethod(
        Invocation.method(
          #cast,
          [],
        ),
        returnValue: <R>[],
      ) as List<R>);

  @override
  _i2.HistoryDto operator [](int? index) => (super.noSuchMethod(
        Invocation.method(
          #[],
          [index],
        ),
        returnValue: _FakeHistoryDto_1(
          this,
          Invocation.method(
            #[],
            [index],
          ),
        ),
      ) as _i2.HistoryDto);

  @override
  void operator []=(
    int? index,
    _i2.HistoryDto? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #[]=,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i2.HistoryDto? value) => super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addAll(Iterable<_i2.HistoryDto>? iterable) => super.noSuchMethod(
        Invocation.method(
          #addAll,
          [iterable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sort(
          [int Function(
            _i2.HistoryDto,
            _i2.HistoryDto,
          )? compare]) =>
      super.noSuchMethod(
        Invocation.method(
          #sort,
          [compare],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void shuffle([_i4.Random? random]) => super.noSuchMethod(
        Invocation.method(
          #shuffle,
          [random],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int indexOf(
    _i2.HistoryDto? element, [
    int? start = 0,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexOf,
          [
            element,
            start,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int indexWhere(
    bool Function(_i2.HistoryDto)? test, [
    int? start = 0,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexWhere,
          [
            test,
            start,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int lastIndexWhere(
    bool Function(_i2.HistoryDto)? test, [
    int? start,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastIndexWhere,
          [
            test,
            start,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int lastIndexOf(
    _i2.HistoryDto? element, [
    int? start,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastIndexOf,
          [
            element,
            start,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void insert(
    int? index,
    _i2.HistoryDto? element,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            index,
            element,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void insertAll(
    int? index,
    Iterable<_i2.HistoryDto>? iterable,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #insertAll,
          [
            index,
            iterable,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAll(
    int? index,
    Iterable<_i2.HistoryDto>? iterable,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAll,
          [
            index,
            iterable,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool remove(Object? value) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [value],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.HistoryDto removeAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeAt,
          [index],
        ),
        returnValue: _FakeHistoryDto_1(
          this,
          Invocation.method(
            #removeAt,
            [index],
          ),
        ),
      ) as _i2.HistoryDto);

  @override
  _i2.HistoryDto removeLast() => (super.noSuchMethod(
        Invocation.method(
          #removeLast,
          [],
        ),
        returnValue: _FakeHistoryDto_1(
          this,
          Invocation.method(
            #removeLast,
            [],
          ),
        ),
      ) as _i2.HistoryDto);

  @override
  void removeWhere(bool Function(_i2.HistoryDto)? test) => super.noSuchMethod(
        Invocation.method(
          #removeWhere,
          [test],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void retainWhere(bool Function(_i2.HistoryDto)? test) => super.noSuchMethod(
        Invocation.method(
          #retainWhere,
          [test],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i2.HistoryDto> operator +(List<_i2.HistoryDto>? other) =>
      (super.noSuchMethod(
        Invocation.method(
          #+,
          [other],
        ),
        returnValue: <_i2.HistoryDto>[],
      ) as List<_i2.HistoryDto>);

  @override
  List<_i2.HistoryDto> sublist(
    int? start, [
    int? end,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #sublist,
          [
            start,
            end,
          ],
        ),
        returnValue: <_i2.HistoryDto>[],
      ) as List<_i2.HistoryDto>);

  @override
  Iterable<_i2.HistoryDto> getRange(
    int? start,
    int? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRange,
          [
            start,
            end,
          ],
        ),
        returnValue: <_i2.HistoryDto>[],
      ) as Iterable<_i2.HistoryDto>);

  @override
  void setRange(
    int? start,
    int? end,
    Iterable<_i2.HistoryDto>? iterable, [
    int? skipCount = 0,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #setRange,
          [
            start,
            end,
            iterable,
            skipCount,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeRange(
    int? start,
    int? end,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeRange,
          [
            start,
            end,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fillRange(
    int? start,
    int? end, [
    _i2.HistoryDto? fillValue,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #fillRange,
          [
            start,
            end,
            fillValue,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void replaceRange(
    int? start,
    int? end,
    Iterable<_i2.HistoryDto>? replacements,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #replaceRange,
          [
            start,
            end,
            replacements,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<int, _i2.HistoryDto> asMap() => (super.noSuchMethod(
        Invocation.method(
          #asMap,
          [],
        ),
        returnValue: <int, _i2.HistoryDto>{},
      ) as Map<int, _i2.HistoryDto>);

  @override
  Iterable<_i2.HistoryDto> followedBy(Iterable<_i2.HistoryDto>? other) =>
      (super.noSuchMethod(
        Invocation.method(
          #followedBy,
          [other],
        ),
        returnValue: <_i2.HistoryDto>[],
      ) as Iterable<_i2.HistoryDto>);

  @override
  Iterable<T> map<T>(T Function(_i2.HistoryDto)? toElement) =>
      (super.noSuchMethod(
        Invocation.method(
          #map,
          [toElement],
        ),
        returnValue: <T>[],
      ) as Iterable<T>);

  @override
  Iterable<_i2.HistoryDto> where(bool Function(_i2.HistoryDto)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #where,
          [test],
        ),
        returnValue: <_i2.HistoryDto>[],
      ) as Iterable<_i2.HistoryDto>);

  @override
  Iterable<T> whereType<T>() => (super.noSuchMethod(
        Invocation.method(
          #whereType,
          [],
        ),
        returnValue: <T>[],
      ) as Iterable<T>);

  @override
  Iterable<T> expand<T>(Iterable<T> Function(_i2.HistoryDto)? toElements) =>
      (super.noSuchMethod(
        Invocation.method(
          #expand,
          [toElements],
        ),
        returnValue: <T>[],
      ) as Iterable<T>);

  @override
  bool contains(Object? element) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [element],
        ),
        returnValue: false,
      ) as bool);

  @override
  void forEach(void Function(_i2.HistoryDto)? action) => super.noSuchMethod(
        Invocation.method(
          #forEach,
          [action],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.HistoryDto reduce(
          _i2.HistoryDto Function(
            _i2.HistoryDto,
            _i2.HistoryDto,
          )? combine) =>
      (super.noSuchMethod(
        Invocation.method(
          #reduce,
          [combine],
        ),
        returnValue: _FakeHistoryDto_1(
          this,
          Invocation.method(
            #reduce,
            [combine],
          ),
        ),
      ) as _i2.HistoryDto);

  @override
  T fold<T>(
    T? initialValue,
    T Function(
      T,
      _i2.HistoryDto,
    )? combine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fold,
          [
            initialValue,
            combine,
          ],
        ),
        returnValue: _i5.dummyValue<T>(
          this,
          Invocation.method(
            #fold,
            [
              initialValue,
              combine,
            ],
          ),
        ),
      ) as T);

  @override
  bool every(bool Function(_i2.HistoryDto)? test) => (super.noSuchMethod(
        Invocation.method(
          #every,
          [test],
        ),
        returnValue: false,
      ) as bool);

  @override
  String join([String? separator = r'']) => (super.noSuchMethod(
        Invocation.method(
          #join,
          [separator],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #join,
            [separator],
          ),
        ),
      ) as String);

  @override
  bool any(bool Function(_i2.HistoryDto)? test) => (super.noSuchMethod(
        Invocation.method(
          #any,
          [test],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.HistoryDto> toList({bool? growable = true}) => (super.noSuchMethod(
        Invocation.method(
          #toList,
          [],
          {#growable: growable},
        ),
        returnValue: <_i2.HistoryDto>[],
      ) as List<_i2.HistoryDto>);

  @override
  Set<_i2.HistoryDto> toSet() => (super.noSuchMethod(
        Invocation.method(
          #toSet,
          [],
        ),
        returnValue: <_i2.HistoryDto>{},
      ) as Set<_i2.HistoryDto>);

  @override
  Iterable<_i2.HistoryDto> take(int? count) => (super.noSuchMethod(
        Invocation.method(
          #take,
          [count],
        ),
        returnValue: <_i2.HistoryDto>[],
      ) as Iterable<_i2.HistoryDto>);

  @override
  Iterable<_i2.HistoryDto> takeWhile(bool Function(_i2.HistoryDto)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #takeWhile,
          [test],
        ),
        returnValue: <_i2.HistoryDto>[],
      ) as Iterable<_i2.HistoryDto>);

  @override
  Iterable<_i2.HistoryDto> skip(int? count) => (super.noSuchMethod(
        Invocation.method(
          #skip,
          [count],
        ),
        returnValue: <_i2.HistoryDto>[],
      ) as Iterable<_i2.HistoryDto>);

  @override
  Iterable<_i2.HistoryDto> skipWhile(bool Function(_i2.HistoryDto)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipWhile,
          [test],
        ),
        returnValue: <_i2.HistoryDto>[],
      ) as Iterable<_i2.HistoryDto>);

  @override
  _i2.HistoryDto firstWhere(
    bool Function(_i2.HistoryDto)? test, {
    _i2.HistoryDto Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #firstWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _FakeHistoryDto_1(
          this,
          Invocation.method(
            #firstWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
      ) as _i2.HistoryDto);

  @override
  _i2.HistoryDto lastWhere(
    bool Function(_i2.HistoryDto)? test, {
    _i2.HistoryDto Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _FakeHistoryDto_1(
          this,
          Invocation.method(
            #lastWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
      ) as _i2.HistoryDto);

  @override
  _i2.HistoryDto singleWhere(
    bool Function(_i2.HistoryDto)? test, {
    _i2.HistoryDto Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #singleWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _FakeHistoryDto_1(
          this,
          Invocation.method(
            #singleWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
      ) as _i2.HistoryDto);

  @override
  _i2.HistoryDto elementAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #elementAt,
          [index],
        ),
        returnValue: _FakeHistoryDto_1(
          this,
          Invocation.method(
            #elementAt,
            [index],
          ),
        ),
      ) as _i2.HistoryDto);
}
